.TH STRTRIM 3 "November 2023" "42 Quebec"
.SH NAME
     strtrim \- trim characters from the beginning and end of a string

LIBRARY
     Your Library (libYourLibrary, -lYourLibrary)

SYNOPSIS
     #include <libft.h>
     .br
     char *strtrim(char const *s1, char const *set);

DESCRIPTION
     The \fBstrtrim\fR function allocates and returns a new string that is a copy of \fIs1\fR with leading and trailing characters specified in \fIset\fR removed.

.PP
     If either \fIs1\fR or \fIset\fR is \fBNULL\fR, the function returns \fBNULL\fR, indicating a failure to trim.

.PP
     The resulting string is created by dynamically allocating memory using \fBmalloc\fR, and the trimming is performed by removing characters from \fIs1\fR that match any character in \fIset\fR from the beginning and end of the string.

.PP
     The allocated memory is automatically null-terminated.

RETURN VALUES
     The \fBstrtrim\fR function returns a pointer to the newly allocated trimmed string, or \fBNULL\fR if the allocation fails.

EXAMPLES
     The following example demonstrates the usage of \fBstrtrim\fR:
     .br
     #include <libft.h>
     .br
     char *result = strtrim("   Hello, world!   ", " ");
     printf("%s\n", result);
     free(result);

SEE ALSO
     ft_calloc(3), ft_strlen(3)

AUTHOR
     Created by oforest <oforest@student.42quebec.com>

HISTORY
     The \fBstrtrim\fR function is part of the 42 Library and was created in November 2023.
